### ISSUE TITLE
perfectlighbox 4.0.2. missing "Classes"

### ISSUE THREAD

**Issue by martinwb** [lochmueller/perfectlightbox#1]
Hi!

Trying to install the perfectlightbox 4.0.2 in Typo3 7.6.9 i get the following eror message:

"Could not scan for classes inside "/typo3conf/ext/perfectlightbox/Classes/" which does not appear to be a file nor a folder" 

The extension is not installed.

**Comment by lochmueller** [comment]
It seems to be a wrong autoloader configuration, because the classes are not migrated yet:
`"autoload": {
    "psr-4": {
      "BENIEDIEK\\Perfectlightbox\\": "Classes/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "BENIEDIEK\\Perfectlightbox\\Tests\\": "Tests",
      "TYPO3\\CMS\\Core\\Tests\\": ".Build/vendor/typo3/cms/typo3/sysext/core/Tests/"
    }
},`
