### ISSUE TITLE
Call to undefined method TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer::IMAGE()

### ISSUE THREAD

**Issue by sterborg** [lochmueller/perfectlightbox#12]
Error thrown in file
Classes/Perfectlightbox.php in line 171

Possible solution:
Replace

`$theImgCode .= $pObj->local_cObj->IMAGE($lConf['image.']) . $pObj->local_cObj->stdWrap(`

with

`$theImgCode .= $pObj->local_cObj->cObjGetSingle('IMAGE', $lConf['image.']) . $pObj->local_cObj->stdWrap(`

in line 171.

**Comment by lochmueller** [comment]
Good point. Is changed in current master 👍

**Comment by kitzberger** [comment]
Thanks, it's working! Care to put a new release to packagist and TER?
