### ISSUE TITLE
Usage of deprecated each() function

### ISSUE THREAD

**Issue by chrisprog20** [lochmueller/perfectlightbox#13]
Hello, 

in version 4.1.4 in Classes/Perfectlightbox.php you use the each() function in line 145.
This expression is[ deprecated since PHP 7.2](http://php.net/manual/en/function.each.php).
Therefore I think you can savely replace the expression
```
while(list(, $val)) = each($imgs)) {
...
}
```
by
```
foreach($imgs as $val) {
...
}
```
I have tested it with this and I did not find any errors :)

Cheers
Christian

**Comment by lochmueller** [comment]
Thanks for the report. Fixed in current master 👍

**Comment by chrisprog20** [comment]
Great! That's so cool that you reacted this fast. Then I can remove again my customization from your great extension! :)
