### ISSUE TITLE
9LTS

### ISSUE THREAD

**Issue by PeterMeiningen** [lochmueller/perfectlightbox#16]
Will there be a release for 9lts in the future

**Comment by lochmueller** [comment]
@PeterMeiningen It is not decided yet. I is based on the contribution, if there are more release, because my focus is on other extensions at the moment...

**Comment by kaystrobach** [comment]
@PeterMeiningen can you provide a list of problems in v9 LTS, maybe i find the time to get it running.

**Comment by lochmueller** [comment]
Hey @kaystrobach thanks for your "pushing" ;) Feel free to send a pull request. If the EXT is done for TYPO3 9.x I could release/push it to TER.

**Comment by lochmueller** [comment]
I fixed the current master to 5.0.0-dev and allow TYPO3 8.x and 9.x I also rework the extension structure to fit the new folder name structure. Please check the extension in your envs and create issues for single problems.

I will close this - general task - now....

**Comment by kaystrobach** [comment]
thx

**Comment by franzholz** [comment]
When will a version for TYPO3 9.5 be published on TYPO3 TER?
