### ISSUE TITLE
Overlay is on top of everything

### ISSUE THREAD

**Issue by c27e27** [lochmueller/perfectlightbox#18]
I installed pefectlightbox in TYPO3 7.6.31 and used it with jquery and found this failure: In line 45 of slimbox.2.0.4.js the overlay is not just added to the elements for close clicks, but will be appended (moved) as a child to the bottom div. I removed the ".add(overlay)" in this line and inserted a ".click(close)[0]" to the line 31 and now it works.

**Comment by lochmueller** [comment]
Perhaps this is already fixed in current master: https://github.com/lochmueller/perfectlightbox/commit/13e06380634352371283b270094dd66ee40014c5

**Comment by lochmueller** [comment]
I close this issue. I think the problem solved in the current master.
