### ISSUE TITLE
Release of version 5

### ISSUE THREAD

**Issue by xQuai** [lochmueller/perfectlightbox#19]
Hi,

it is not a real mistake. I just wanted to ask when version 5 will be released.

Thank you very much for your answer.

Regards
xQuai

**Comment by lochmueller** [comment]
Hey @xQuai ,
I don't know :-/ Feel free to use the curretn dev-master with composer. Currently There is not much time for testing the extnsion with new TYPO3 versions.
Regards,
Tim
