### ISSUE TITLE
Click-enlarge doesn't work

### ISSUE THREAD

**Issue by oirad21** [lochmueller/perfectlightbox#3]
I've installed perfectlightbox 4.0.2 on a typo3 7.6.5. After the installation I didn't get the usual message that the extension has been installed.

I could include it into the template tho, and the checkboxes Click to enlarge, lightbox, group, presentation and slideshow exist in the backend when adding images.

When I activate Click to enlarge and lightbox, the anchor attribute of the image does get the class "lightbox", but the click to enlarge effect isn't lightbox. It's still the usual link to the image.

I tried deactivating the extenstion and then activating it. When i pressed Activate i got the error: 

'Could not scan for classes inside "/home/httpd/vhosts/primelite.ch/preview.primelite.ch/typo3conf/ext/perfectlightbox/Classes/" which does not appear to be a file nor a folder'

Any help?

Thanks in advance

**Comment by lochmueller** [comment]
See https://github.com/beniediek/perfectlightbox/issues/1
We will fix this in the next days/weeks...
