### ISSUE TITLE
TYPO3 8 support?

### ISSUE THREAD

**Issue by CDRO** [lochmueller/perfectlightbox#8]
Is it planned to release a version that is compatible with TYPO3 8?

**Comment by lochmueller** [comment]
New Version is already for composer. Run:
composer require lochmueller/perfectlightbox

TER release will follow shortly...

Regards,
Tim

**Comment by LeoniePhiline** [comment]
*bump* :)

Could you please release on TER? Thanks!

**Comment by lochmueller** [comment]
I ask @beniediek for the extension key. If he transfer the extension key to my account, i will release the new version shortly...

**Comment by fabtho** [comment]
bump, would still be cool have this in TER. @beniediek?
